#%RAML 0.8
title: The API Title
baseUri: https://{environment}
baseUriParameters:
  environment:
    enum: [api.di.net,api.live.biz.co.nz,api-internal.test.net,api.preprod.net,api-internal.dev.net,api.dev.net,api.test.net]
documentation:
- title: Description
  content: ''
- title: History
  content: !include documentation/history.md
- title: Effort
  content: !include documentation/effort.md
securitySchemes: !include security-schemas-basic.raml
traits: !include traits.raml
resourceTypes: !include resource-types.raml
schemas:
- infoSchema: !include schemas/ErrorResponse.json
- dessertSchema: !include schemas/Dessert.json
- fruitSchema: !include schemas/Fruit.json
/root-resource:
  uriParameters: {}
  /child-resource:
    uriParameters: {}
    type:
      item-put:
        infoSchema: infoSchema
        reqSchema: dessertSchema
        respSchema: dessertSchema
        sample400Resp: !include samples/sample400BadRequest-sample.json
        sample401Resp: !include samples/sample401-Unauthorized-sample.json
        sample403Resp: !include samples/sample403-Forbidden-sample.json
        sample404Resp: !include samples/sample404Resp-sample.json
        sample405Resp: !include samples/sample405-MethodNotAllowed-sample.json
        sample406Resp: !include samples/sample406-NotAcceptable-sample.json
        putSample200Resp: !include samples/dessert-sample.Dessert.json
        putSampleReq: !include samples/dessert-sample.Dessert.json
    put:
      description: >+
        The put method description

  type:
    item-get:
      infoSchema: infoSchema
      respSchema: fruitSchema
      sample400Resp: !include samples/sample400BadRequest-sample.json
      sample401Resp: !include samples/sample401-Unauthorized-sample.json
      sample403Resp: !include samples/sample403-Forbidden-sample.json
      sample404Resp: !include samples/sample404Resp-sample.json
      sample405Resp: !include samples/sample405-MethodNotAllowed-sample.json
      sample406Resp: !include samples/sample406-NotAcceptable-sample.json
      sample200Resp: !include samples/fruit-sample.Fruit.json
  get:
    description: >+
      The get method description

    queryParameters:
      species:
        description: >+
          The species of fruit

